server:
  port: 8091
spring:
  data:
    mongodb:
      database: productdb
#      host: 127.0.0.1
#      port: 27017
#      username: admin
#      password: admin
#      authentication-database: admin

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.4.1
