version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - c:/tmp/mongo:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081